// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(FacultyDbContext))]
    [Migration("20251129021936_mm")]
    partial class mm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Course", b =>
                {
                    b.Property<int>("Crs_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Crs_ID"));

                    b.Property<int>("Credit_Hours")
                        .HasColumnType("int");

                    b.Property<string>("Crs_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Dept_ID")
                        .HasColumnType("int");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Doc_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Max_Num_Stu")
                        .HasColumnType("int");

                    b.HasKey("Crs_ID");

                    b.HasIndex("Dept_ID");

                    b.HasIndex("Doc_ID");

                    b.ToTable("Course", "Faculty");
                });

            modelBuilder.Entity("api.Models.CourseSchedule", b =>
                {
                    b.Property<int>("Sch_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sch_ID"));

                    b.Property<int>("Crs_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<TimeSpan>("END_Hour")
                        .HasColumnType("time");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("Start_Hour")
                        .HasColumnType("time");

                    b.HasKey("Sch_ID", "Crs_ID");

                    b.HasIndex("Crs_ID");

                    b.ToTable("Course_Schedule", "Faculty", t =>
                        {
                            t.HasCheckConstraint("CK_Day", "[Day] IN ('Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday')");
                        });
                });

            modelBuilder.Entity("api.Models.Department", b =>
                {
                    b.Property<int>("Dept_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dept_ID"));

                    b.Property<string>("Dept_Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Dept_Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dept_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Doc_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Establish_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Dept_ID");

                    b.HasIndex("Doc_ID");

                    b.ToTable("Departement", "Faculty");
                });

            modelBuilder.Entity("api.Models.Doctor", b =>
                {
                    b.Property<int>("Doc_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Doc_ID"));

                    b.Property<int?>("Age")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(YEAR(GETDATE()) - YEAR([DOB]))");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dept_ID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("Hire_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hour_Rate")
                        .HasColumnType("int");

                    b.Property<int>("Hours_Per_Week")
                        .HasColumnType("int");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("Salary")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("([Hour_Rate] * [Hours_Per_Week] * 4)", true);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Doc_ID");

                    b.HasIndex("Dept_ID");

                    b.ToTable("Doctor", "Faculty", t =>
                        {
                            t.HasCheckConstraint("CK_Gender_Doctor", "[Gender] IN ('F', 'M')");
                        });
                });

            modelBuilder.Entity("api.Models.DoctorAddress", b =>
                {
                    b.Property<int>("Doc_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.HasKey("Doc_ID", "City", "Street");

                    b.ToTable("Doctor_Address", "Faculty");
                });

            modelBuilder.Entity("api.Models.DoctorPhone", b =>
                {
                    b.Property<int>("Doc_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Phone_NUM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.HasKey("Doc_ID", "Phone_NUM");

                    b.ToTable("Doctor_Phone", "Faculty");
                });

            modelBuilder.Entity("api.Models.Enrollement", b =>
                {
                    b.Property<int>("Stu_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Crs_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Year")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnOrder(2);

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.HasKey("Stu_ID", "Crs_ID", "Year");

                    b.HasIndex("Crs_ID");

                    b.ToTable("Enrollement", "Faculty", t =>
                        {
                            t.HasCheckConstraint("CK_Grade", "[Grade] >= 0 AND [Grade] <= 100");
                        });
                });

            modelBuilder.Entity("api.Models.Student", b =>
                {
                    b.Property<int>("Stu_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stu_ID"));

                    b.Property<int?>("Age")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(YEAR(GETDATE()) - YEAR([DOB]))");

                    b.Property<decimal>("CGPA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dept_ID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Stu_SSN")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Stu_ID");

                    b.HasIndex("Dept_ID");

                    b.ToTable("Student", "Faculty", t =>
                        {
                            t.HasCheckConstraint("CK_Gender_Student", "[Gender] IN ('F', 'M')");

                            t.HasCheckConstraint("CK_Level", "[Level] >= 1 AND [Level] <= 4");
                        });
                });

            modelBuilder.Entity("api.Models.StudentAddress", b =>
                {
                    b.Property<int>("Stu_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.HasKey("Stu_ID", "City", "Street");

                    b.ToTable("Student_Address", "Faculty");
                });

            modelBuilder.Entity("api.Models.StudentPhone", b =>
                {
                    b.Property<int>("Stu_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Phone_NUM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.HasKey("Stu_ID", "Phone_NUM");

                    b.ToTable("Student_Phone", "Faculty");
                });

            modelBuilder.Entity("api.Models.Teach", b =>
                {
                    b.Property<int>("Crs_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Doc_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Semester")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.HasKey("Crs_ID", "Doc_ID", "Semester");

                    b.HasIndex("Doc_ID");

                    b.ToTable("Teach", "Faculty");
                });

            modelBuilder.Entity("api.Models.Course", b =>
                {
                    b.HasOne("api.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("Dept_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api.Models.Doctor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("Doc_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("api.Models.CourseSchedule", b =>
                {
                    b.HasOne("api.Models.Course", "Course")
                        .WithMany("Schedules")
                        .HasForeignKey("Crs_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("api.Models.Department", b =>
                {
                    b.HasOne("api.Models.Doctor", "HeadDoctor")
                        .WithMany()
                        .HasForeignKey("Doc_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HeadDoctor");
                });

            modelBuilder.Entity("api.Models.Doctor", b =>
                {
                    b.HasOne("api.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("Dept_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("api.Models.DoctorAddress", b =>
                {
                    b.HasOne("api.Models.Doctor", "Doctor")
                        .WithMany("Addresses")
                        .HasForeignKey("Doc_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("api.Models.DoctorPhone", b =>
                {
                    b.HasOne("api.Models.Doctor", "Doctor")
                        .WithMany("Phones")
                        .HasForeignKey("Doc_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("api.Models.Enrollement", b =>
                {
                    b.HasOne("api.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("Crs_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("Stu_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("api.Models.Student", b =>
                {
                    b.HasOne("api.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("Dept_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("api.Models.StudentAddress", b =>
                {
                    b.HasOne("api.Models.Student", "Student")
                        .WithMany("Addresses")
                        .HasForeignKey("Stu_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("api.Models.StudentPhone", b =>
                {
                    b.HasOne("api.Models.Student", "Student")
                        .WithMany("Phones")
                        .HasForeignKey("Stu_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("api.Models.Teach", b =>
                {
                    b.HasOne("api.Models.Course", "Course")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("Crs_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Doctor", "Doctor")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("Doc_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("api.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Schedules");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("api.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Doctors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("api.Models.Doctor", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Courses");

                    b.Navigation("Phones");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("api.Models.Student", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Enrollments");

                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
